"""Citation builder.

Citations are constructed *programmatically* from the sources that were
actually placed in the LLM's context — never generated by the LLM itself.
This is what makes fabricated citations structurally impossible.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional

from langchain_core.documents import Document


@dataclass
class Citations:
    """Internal and external sources behind one answer."""

    internal: List[str] = field(default_factory=list)
    external: List[Dict[str, str]] = field(default_factory=list)

    @property
    def is_empty(self) -> bool:
        return not self.internal and not self.external

    def as_dict(self) -> Dict[str, object]:
        return {"internal": self.internal, "external": self.external}


class CitationBuilder:
    """Formats and deduplicates source citations."""

    def build(
        self,
        internal_docs: List[Document],
        web_docs: List[Document],
        rate_docs: Optional[List[Document]] = None,
    ) -> Citations:
        """Build citations from the exact documents the LLM saw."""
        citations = Citations()

        seen_internal = set()
        for document in internal_docs:
            label = self._internal_label(document)
            if label not in seen_internal:
                seen_internal.add(label)
                citations.internal.append(label)

        seen_urls = set()
        for document in web_docs:
            url = document.metadata.get("url", "")
            if url and url not in seen_urls:
                seen_urls.add(url)
                citations.external.append(
                    {"title": document.metadata.get("title", url), "url": url}
                )

        # Rate quotes are their own kind of source: credit each distinct carrier
        # (they carry no URL, so they land in `external` with an empty link).
        seen_rate = set()
        for document in rate_docs or []:
            meta = document.metadata
            carrier = meta.get("carrier", "carrier")
            key = (carrier, meta.get("mode", ""))
            if key in seen_rate:
                continue
            seen_rate.add(key)
            provider = meta.get("provider", "rate provider")
            citations.external.append(
                {"title": f"{carrier} live rate (via {provider})", "url": ""}
            )
        return citations

    @staticmethod
    def _internal_label(document: Document) -> str:
        """Human-readable provenance: 'Manual.pdf, page 12' / 'SOP.md — Receiving'."""
        meta = document.metadata
        label = meta.get("filename", "unknown document")
        if "page" in meta:
            label += f", page {meta['page']}"
        elif "section_title" in meta:
            label += f" — {meta['section_title']}"
        elif "rows" in meta:
            label += f", rows {meta['rows']}"
        return label
